#!/usr/bin/env bash

# Allows for adding tasks and immediately completing them
# Transforms due:today -> due:2020-09-07

action=$1
shift;

[ "$action" = "usage" ] && {
  echo "  Customized add:"
  echo "    add x \"THING I NEEDED TO DO RIGHT NOW\""
  echo "      add an item and mark it as done in one step"
  echo ""
  exit
}

DO=false

if [ "$1" = "x" ]; then
  DO=true
  shift
fi

# Remaining args
today=$(date '+%Y-%m-%d')
task=$(echo "$@" | sed  "s/due:today/due:$today/")

if "$TODO_SH" command add "$task"; then
  # getting the number item: it's simply the last item added to the file
  line=`wc -l "$TODO_FILE" | sed 's/^ *//g' | cut -d' ' -f1`
  $DO && "$TODO_SH" command do "$line"
fi
