#!/usr/bin/env bash
set -e

export DOTFILES=$HOME/dotfiles

# Bring in some colors
source init/logger

is_mac() {
    [[ "$OSTYPE" =~ ^darwin ]] || return 1
}

# Uses the local template and copies it into the `link` folder so that we can
# ignore potentially private git things
setup_gitconfig() {
    if ! [ -f gitconfig.local ]
    then
        info "Setting up local git config"

        git_credential='cache'
        if is_mac
        then
            git_credential='osxkeychain'
        fi

        user 'What is your github author name?'
        read -e git_authorname
        user 'What is your github author email?'
        read -e git_authoremail

        sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" init/template/gitconfig.local > gitconfig.local

        success 'Local git config complete.'
    fi
}

# HOMEBREW
brew_install() {
    info "Installing Homebrew"
    if test ! $(which /usr/local/bin/brew)
    then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        export PATH="/usr/local/bin:$PATH"
    else
        success "Homebrew already installed."
    fi
}

brew_update() {
    info "Brew update"
    brew update
}

brew_bundle() {
    info "Brew bundle"
    brew bundle
}

homebrew() {
    cd "init"
    brew_install
    brew_update
    brew bundle
    brew install neovim/neovim/neovim
    cd "../"
}

# Zsh
zsh() {
    info "Installing zsh syntax highlighting"
    if ! [ -d zsh/plugins/zsh-syntax-highlighting ]
    then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git zsh/plugins/zsh-syntax-highlighting
    else
        success "Syntax highlighting already installed."
    fi

    info "Installing pure prompt"
    if ! [ -d zsh/plugins/pure ]
    then
        git clone git@github.com:sindresorhus/pure.git zsh/plugins/pure
    else
        success "Pure prompt already installed."
    fi
}

change_shell() {
    echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
}

# pip
do_python() {
    info "Installing neovim via Python3"
    pip3 install neovim
    success "Done!"
}

# Node
do_node() {
    if ! [ -f bin/nave.sh ]
    then
        info "Installing Nave for Node stuff"
        curl -fsSL https://raw.githubusercontent.com/isaacs/nave/master/nave.sh > bin/nave.sh
        chmod u+x bin/nave.sh
    fi
}


link_files() {
    info "Linking dotfiles"
    rcup -x init -x readme.md
}

osx_defaults() {
    info "Setting system defaults"
    ~./bin/osx
}

clean_up() {
    success "Done!  Run 'source ~/.zshrc' to see changes."
}

setup_gitconfig
homebrew
do_python
do_node
zsh
change_shell
link_files
osx_defaults
clean_up
