#!/usr/bin/env bash
set -e

export DOTFILES=$HOME/dotfiles

# Bring in some colors
source init/logger

is_mac() {
    [[ "$OSTYPE" =~ ^darwin ]] || return 1
}

append_to_zshrc() {
  fancy_echo 'Setting up $PATH in zshrc'
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >> "$zshrc"
    else
      printf "\\n%s\\n" "$text" >> "$zshrc"
    fi
  fi
}


# HOMEBREW
setup_homebrew() {
    info "Installing Homebrew"
    if test ! $(which /usr/local/bin/brew)
    then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    else
        success "Homebrew already installed."
    fi

    brew update --force

    brew bundle --file=-<<EOF
    cask_args appdir: '/Applications'

    tap 'homebrew/bundle'
    tap 'thoughtbot/formulae'
    tap "homebrew/cask"

    brew "bat"
    brew "git"
    brew "hub"
    brew "rcm"
    brew "ripgrep"
    brew "zsh"
    brew "neovim"

    cask "alfred"
    cask "kitty"
EOF
}

# Zsh
zsh() {
    info "Installing zsh syntax highlighting"
    if ! [ -d zsh/plugins/zsh-syntax-highlighting ]
    then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git zsh/plugins/zsh-syntax-highlighting
    else
        success "Syntax highlighting already installed."
    fi

    info "Installing zsh autosuggestion"
    if ! [ -d zsh/plugins/zsh-autosuggestions ]
    then
        git clone git://github.com/zsh-users/zsh-autosuggestions zsh/plugins/zsh-autosuggestions
    else
        success "ZSH autosuggestions already installed."
    fi

    info "Installing z"
    if ! [ -d zsh/plugins/z ]
    then
        git clone git@github.com:rupa/z.git zsh/plugins/z
    else
        success "Z already installed."
    fi

}

link_files() {
    info "Linking dotfiles"
    rcup -x init -x readme.md
}

osx_defaults() {
    if [ ! -d "$HOME/.bin/" ]; then
      mkdir "$HOME/.bin"
    fi
    info "Setting system defaults"
    $HOME/.bin/osx
}

clean_up() {
    success "Done!  Run 'source ~/.zshrc' to see changes."
}

setup_homebrew
zsh
link_files
osx_defaults
clean_up
