#!/bin/bash

# I stole most of this from
# https://github.com/garybernhardt/dotfiles/blob/master/.githelpers

HASH="%C(always,yellow)%h%C(always,reset)"
RELATIVE_TIME="%C(always,green)(%ar)%C(always,reset)"
AUTHOR="%<(10)%C(always,bold blue)%an%C(reset)"
REFS="%C(always,red)%d%C(always,reset)"
SUBJECT="%s"

FORMAT="$HASH $RELATIVE_TIME $AUTHOR $REFS $SUBJECT"

BRANCH_PREFIX="%(HEAD)"
BRANCH_REF="%(color:red)%(color:bold)%(refname:short)%(color:reset)"
BRANCH_HASH="%(color:yellow)%(objectname:short)%(color:reset)"
BRANCH_DATE="%(color:green)(%(committerdate:relative))%(color:reset)"
BRANCH_AUTHOR="%(color:blue)%(color:bold)<%(authorname)>%(color:reset)"
BRANCH_CONTENTS="%(contents:subject)"

BRANCH_FORMAT="$BRANCH_PREFIX}$BRANCH_REF}$BRANCH_HASH}$BRANCH_DATE}$BRANCH_AUTHOR}$BRANCH_CONTENTS"

DIFF_BRANCH_FORMAT="$HASH}$RELATIVE_TIME}$AUTHOR} $SUBJECT"

show_git_head() {
  pretty_git_log -1
  git show -p --pretty="tformat:"
}

# Format like
# hash    (8 hours ago)    Nick Ball    Did something
# hash    (15 hours ago)   Nick Ball    Did something else
pretty_git_log() {
    git log --graph --pretty="tformat:${FORMAT}" --no-show-signature $* | git_page_maybe
}

pretty_git_branch() {
  git branch -v --color=always --format=${BRANCH_FORMAT} $* | pretty_git_format
}

pretty_git_diff_branch() {
  git log --graph --color=always --pretty="tformat:${DIFF_BRANCH_FORMAT}" --no-merges $* | pretty_git_format
}

pretty_git_branch_sorted() {
  git branch -v --color=always --format=${BRANCH_FORMAT} --sort=-committerdate $* | pretty_git_format
}

pretty_git_format() {

    # Replace (2 years ago) with (2 years)
    sed -Ee 's/(^[^<]*) ago\)/\1)/' |
    # Replace (2 years, 5 months) with (2 years)
    sed -Ee 's/(^[^<]*), [[:digit:]]+ .*months?\)/\1)/' |
    # Line columns up based on } delimiter
    column -s '}' -t
}

git_page_maybe() {
  if [ -n "$GIT_NO_PAGER" ]; then
    cat
  else
    less --quit-if-one-screen --no-init --RAW-CONTROL-CHARS --chop-long-lines
  fi
}
